name: ble_thermal_printer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.34.5
  esc_pos_printer: ^4.1.0
  # blue_thermal_printer: ^1.2.3
  esc_pos_utils: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
